# Generated by Django 5.1.2 on 2024-10-19 17:30

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_purchasedcrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('timestamp', models.FloatField(default=time.time)),
                ('transactions', models.JSONField(default=list)),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
