# Generated by Django 5.0.6 on 2024-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_crop_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
