# Generated by Django 5.1.2 on 2024-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0007_crop_price_in_tokens_crop_token_currency_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='token_balance',
            new_name='balance',
        ),
    ]
