# Generated by Django 5.0.6 on 2024-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0009_alter_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='specific_user_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
