# Generated by Django 5.0.6 on 2024-10-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0011_userspecificcrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecificcrop',
            name='specific_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
