# Generated by Django 5.0.6 on 2024-10-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0012_alter_userspecificcrop_specific_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecificcrop',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
